### ISSUE TITLE
Question Regarding Potential Clean & Optimization

### ISSUE THREAD

**Issue by ghost** [igorsinkovec/shell_scripts#1]
Regarding the `usr/local/bin/battery` file, and its `divide_and_round()` function:

If `$1` is `100`, the following...

```bash
awk -v N="$1" 'BEGIN{printf("%.1d", (N*0.01)+0.5)}'
```

...would output `1`, rounding down by default. Is that what you really wanted? Yours, however, at least for me, yielded `.1` which seems peculiar. If the value is _always_ prepended with a  `.`, then you can just prepend it manually in the `awk` use above. 

Also, could you by any chance post an exact replica of your output for the battery script? I   think I could greatly improve it, but I unfortunately would be working blind, as I don't have  a battery in this computer. lol

Actually, the original output _and_ what this script outputs. It would help me elsewhere, too.

You might, for example, want this:

```bash
divide_and_round() {
  awk -v I="$1" 'BEGIN{printf("%d\n", (I*0.01)+0.5)}'
}
```

Then you could do this on line 132, in the `info()` function:

```bash
local power=$(divide_and_round $(value_of "$bat/power_now" "$(get_stat)"))
```

**Comment by igorsinkovec** [comment]
Hey, I just read your message :) Thanks for writing and sorry I didn't notice your message sooner. 

Truth is I don't really use this script any more. Let me know if you still want to work on it and I'll send you the info you wanted.

**Comment by ghost** [comment]
Wow, that's a very late reply. Lol But it's OK. I'll just leave it as it is, especially if you don't use the script, but if you happen to find this Issue useful, that'd be good.
